use serde::Serialize;

use crate::config::ProviderKind;

pub const DOMESTIC_PROVIDERS: &[ProviderKind] = &[
    ProviderKind::Deepseek,
    ProviderKind::Xiaomi,
    ProviderKind::Kimi,
    ProviderKind::Zhipu,
    ProviderKind::Minimax,
    ProviderKind::Qwen,
    ProviderKind::Stepfun,
];

#[derive(Debug, Clone, Copy, Serialize)]
pub struct ModelSpec {
    pub provider: ProviderKind,
    pub id: &'static str,
    pub tier: &'static str,
    pub status: &'static str,
    pub is_default: bool,
    pub context_tokens: Option<u64>,
    pub max_output_tokens: Option<u64>,
    pub thinking: &'static str,
    pub reasoning_levels: &'static [&'static str],
    pub cache: &'static str,
    pub tool_use: &'static str,
    pub structured_output: &'static str,
    pub recommended_for: &'static [&'static str],
    pub cli_params: &'static [&'static str],
    pub request_notes: &'static [&'static str],
    pub source: &'static str,
}

#[derive(Debug, Clone, Copy, Serialize)]
pub struct ProviderParamSpec {
    pub provider: ProviderKind,
    pub thinking_mapping: &'static str,
    pub reasoning_effort_mapping: &'static str,
    pub max_tokens_mapping: &'static str,
    pub cache_mapping: &'static str,
    pub supported_cli_params: &'static [&'static str],
    pub passthrough: &'static str,
}

const COMMON_PARAMS: &[&str] = &[
    "--model",
    "--max-tokens",
    "--temperature",
    "--top-p",
    "--presence-penalty",
    "--frequency-penalty",
    "--stop",
    "--param KEY=JSON",
];

const THINKING_PARAMS: &[&str] = &[
    "--thinking enabled|disabled",
    "--max-tokens",
    "--temperature",
    "--top-p",
    "--presence-penalty",
    "--frequency-penalty",
    "--stop",
    "--param KEY=JSON",
];

const DEEPSEEK_PARAMS: &[&str] = &[
    "--thinking enabled|disabled",
    "--reasoning-effort minimal|low|medium|high|max|xhigh",
    "--max-tokens",
    "--temperature",
    "--top-p",
    "--presence-penalty",
    "--frequency-penalty",
    "--stop",
    "--param KEY=JSON",
];

const MINIMAX_PARAMS: &[&str] = &[
    "--model",
    "--max-tokens",
    "--temperature",
    "--top-p",
    "--presence-penalty",
    "--frequency-penalty",
    "--stop",
    "--param service_tier=JSON",
    "--param KEY=JSON",
];

const STEPFUN_PARAMS: &[&str] = &[
    "--model",
    "--reasoning-effort low|medium|high",
    "--max-tokens",
    "--temperature",
    "--top-p",
    "--presence-penalty",
    "--frequency-penalty",
    "--stop",
    "--param KEY=JSON",
];

const DEFAULT_REASONING_LEVELS: &[&str] = &["enabled", "disabled"];
const DEEPSEEK_REASONING_LEVELS: &[&str] = &["minimal", "low", "medium", "high", "max", "xhigh"];
const QWEN_REASONING_LEVELS: &[&str] = &["enabled", "disabled", "budget via model"];
const MINIMAX_REASONING_LEVELS: &[&str] = &["interleaved"];
const STEPFUN_REASONING_LEVELS: &[&str] = &["low", "medium", "high"];
const NO_REASONING_LEVELS: &[&str] = &[];

pub const BUILTIN_MODELS: &[ModelSpec] = &[
    ModelSpec {
        provider: ProviderKind::Deepseek,
        id: "deepseek-v4-pro",
        tier: "flagship",
        status: "current",
        is_default: true,
        context_tokens: Some(1_000_000),
        max_output_tokens: Some(384_000),
        thinking: "toggle; default enabled",
        reasoning_levels: DEEPSEEK_REASONING_LEVELS,
        cache: "provider context cache, cache hit/miss usage exposed",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &["coding agent", "long context", "best DeepSeek quality"],
        cli_params: DEEPSEEK_PARAMS,
        request_notes: &[
            "deepseek-chat and deepseek-reasoner are legacy aliases for v4-flash modes",
        ],
        source: "https://api-docs.deepseek.com/quick_start/pricing/",
    },
    ModelSpec {
        provider: ProviderKind::Deepseek,
        id: "deepseek-v4-flash",
        tier: "fast-budget",
        status: "current",
        is_default: false,
        context_tokens: Some(1_000_000),
        max_output_tokens: Some(384_000),
        thinking: "toggle; default enabled",
        reasoning_levels: DEEPSEEK_REASONING_LEVELS,
        cache: "provider context cache, cache hit/miss usage exposed",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &["cheap coding loops", "fast iteration", "large context"],
        cli_params: DEEPSEEK_PARAMS,
        request_notes: &["FIM is documented for non-thinking mode only"],
        source: "https://api-docs.deepseek.com/quick_start/pricing/",
    },
    ModelSpec {
        provider: ProviderKind::Deepseek,
        id: "deepseek-chat",
        tier: "legacy-alias",
        status: "deprecated-soon",
        is_default: false,
        context_tokens: Some(1_000_000),
        max_output_tokens: Some(384_000),
        thinking: "non-thinking alias for deepseek-v4-flash",
        reasoning_levels: NO_REASONING_LEVELS,
        cache: "provider context cache",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &["compatibility only"],
        cli_params: COMMON_PARAMS,
        request_notes: &["Use deepseek-v4-flash instead for new runs"],
        source: "https://api-docs.deepseek.com/quick_start/pricing/",
    },
    ModelSpec {
        provider: ProviderKind::Deepseek,
        id: "deepseek-reasoner",
        tier: "legacy-alias",
        status: "deprecated-soon",
        is_default: false,
        context_tokens: Some(1_000_000),
        max_output_tokens: Some(384_000),
        thinking: "thinking alias for deepseek-v4-flash",
        reasoning_levels: DEFAULT_REASONING_LEVELS,
        cache: "provider context cache",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &["compatibility only"],
        cli_params: COMMON_PARAMS,
        request_notes: &["Use deepseek-v4-flash with --thinking enabled instead for new runs"],
        source: "https://api-docs.deepseek.com/quick_start/pricing/",
    },
    ModelSpec {
        provider: ProviderKind::Xiaomi,
        id: "mimo-v2.5-pro",
        tier: "flagship-agent",
        status: "current",
        is_default: true,
        context_tokens: Some(1_000_000),
        max_output_tokens: Some(128_000),
        thinking: "toggle",
        reasoning_levels: DEFAULT_REASONING_LEVELS,
        cache: "cache hit/miss usage exposed",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &[
            "complex coding agent",
            "long-range reasoning",
            "large repos",
        ],
        cli_params: THINKING_PARAMS,
        request_notes: &["temperature is omitted automatically when thinking is enabled"],
        source: "https://platform.xiaomimimo.com/docs/en-US/quick-start/model",
    },
    ModelSpec {
        provider: ProviderKind::Xiaomi,
        id: "mimo-v2.5",
        tier: "balanced-omni",
        status: "current",
        is_default: false,
        context_tokens: Some(1_000_000),
        max_output_tokens: Some(128_000),
        thinking: "toggle",
        reasoning_levels: DEFAULT_REASONING_LEVELS,
        cache: "cache hit/miss usage exposed",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &[
            "balanced cost",
            "multimodal-capable accounts",
            "agent tasks",
        ],
        cli_params: THINKING_PARAMS,
        request_notes: &["text chat works through the OpenAI-compatible endpoint"],
        source: "https://platform.xiaomimimo.com/docs/en-US/quick-start/model",
    },
    ModelSpec {
        provider: ProviderKind::Xiaomi,
        id: "mimo-v2-flash",
        tier: "budget-fast",
        status: "current",
        is_default: false,
        context_tokens: Some(256_000),
        max_output_tokens: Some(64_000),
        thinking: "toggle",
        reasoning_levels: DEFAULT_REASONING_LEVELS,
        cache: "cache hit/miss usage exposed",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &["cheap retries", "shorter coding tasks", "fast smoke tests"],
        cli_params: THINKING_PARAMS,
        request_notes: &["lower context and max output than V2.5/V2.5-Pro"],
        source: "https://platform.xiaomimimo.com/docs/en-US/quick-start/model",
    },
    ModelSpec {
        provider: ProviderKind::Xiaomi,
        id: "mimo-v2-pro",
        tier: "legacy-alias",
        status: "deprecated-soon",
        is_default: false,
        context_tokens: Some(1_000_000),
        max_output_tokens: Some(128_000),
        thinking: "toggle",
        reasoning_levels: DEFAULT_REASONING_LEVELS,
        cache: "cache hit/miss usage exposed",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &["compatibility only"],
        cli_params: THINKING_PARAMS,
        request_notes: &[
            "official notice says legacy V2 names auto-route to V2.5 and should migrate",
        ],
        source: "https://platform.xiaomimimo.com/docs",
    },
    ModelSpec {
        provider: ProviderKind::Kimi,
        id: "kimi-k2.6",
        tier: "flagship-agent",
        status: "current",
        is_default: true,
        context_tokens: Some(256_000),
        max_output_tokens: None,
        thinking: "toggle; enabled by default",
        reasoning_levels: DEFAULT_REASONING_LEVELS,
        cache: "prompt_cache_key supported; cache hit/miss usage exposed when returned",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &[
            "coding agent",
            "long-horizon code writing",
            "self-correction",
        ],
        cli_params: THINKING_PARAMS,
        request_notes: &[
            "official docs recommend max_tokens >= 16000 for thinking/tool runs",
            "live API currently accepts only temperature=0.6 and top_p=0.95 for this model",
        ],
        source: "https://platform.kimi.ai/docs/models",
    },
    ModelSpec {
        provider: ProviderKind::Kimi,
        id: "kimi-k2.5",
        tier: "previous-flagship",
        status: "current",
        is_default: false,
        context_tokens: Some(256_000),
        max_output_tokens: None,
        thinking: "toggle",
        reasoning_levels: DEFAULT_REASONING_LEVELS,
        cache: "prompt_cache_key supported",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &["fallback from K2.6", "agent tasks"],
        cli_params: THINKING_PARAMS,
        request_notes: &["prefer kimi-k2.6 for new coding-agent runs"],
        source: "https://platform.kimi.ai/docs/models",
    },
    ModelSpec {
        provider: ProviderKind::Kimi,
        id: "kimi-k2-thinking",
        tier: "thinking",
        status: "current",
        is_default: false,
        context_tokens: Some(256_000),
        max_output_tokens: None,
        thinking: "always enabled",
        reasoning_levels: &["enabled"],
        cache: "prompt_cache_key supported",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &["deep reasoning", "complex multi-step tool use"],
        cli_params: COMMON_PARAMS,
        request_notes: &[
            "dedicated thinking model; Kimi recommends returning reasoning_content in tool loops",
        ],
        source: "https://platform.kimi.ai/docs/guide/use-kimi-k2-thinking-model",
    },
    ModelSpec {
        provider: ProviderKind::Kimi,
        id: "kimi-k2-thinking-turbo",
        tier: "thinking-fast",
        status: "current",
        is_default: false,
        context_tokens: Some(256_000),
        max_output_tokens: None,
        thinking: "always enabled",
        reasoning_levels: &["enabled"],
        cache: "prompt_cache_key supported",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &["faster deep reasoning", "tool-heavy coding"],
        cli_params: COMMON_PARAMS,
        request_notes: &["high-speed thinking model"],
        source: "https://platform.kimi.ai/docs/models",
    },
    ModelSpec {
        provider: ProviderKind::Kimi,
        id: "moonshot-v1-128k",
        tier: "legacy-long-context",
        status: "current",
        is_default: false,
        context_tokens: Some(128_000),
        max_output_tokens: None,
        thinking: "not supported",
        reasoning_levels: NO_REASONING_LEVELS,
        cache: "provider native behavior",
        tool_use: "basic chat",
        structured_output: "basic chat",
        recommended_for: &["cheap legacy text", "long non-agent prompts"],
        cli_params: COMMON_PARAMS,
        request_notes: &["Kimi docs recommend K2.6 for new reasoning/coding work"],
        source: "https://platform.kimi.ai/docs/models",
    },
    ModelSpec {
        provider: ProviderKind::Zhipu,
        id: "glm-5.1",
        tier: "flagship-agent",
        status: "current",
        is_default: true,
        context_tokens: Some(200_000),
        max_output_tokens: Some(128_000),
        thinking: "toggle",
        reasoning_levels: DEFAULT_REASONING_LEVELS,
        cache: "context cache; cache hit/miss usage exposed",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &[
            "agentic coding",
            "long autonomous tasks",
            "highest GLM quality",
        ],
        cli_params: THINKING_PARAMS,
        request_notes: &["official docs position GLM-5.1 for long coding-agent work"],
        source: "https://docs.bigmodel.cn/cn/guide/models/text/glm-5.1",
    },
    ModelSpec {
        provider: ProviderKind::Zhipu,
        id: "glm-5.1-highspeed",
        tier: "flagship-fast",
        status: "enterprise",
        is_default: false,
        context_tokens: Some(200_000),
        max_output_tokens: Some(128_000),
        thinking: "toggle",
        reasoning_levels: DEFAULT_REASONING_LEVELS,
        cache: "context cache",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &["enterprise low latency", "same GLM-5.1 capability"],
        cli_params: THINKING_PARAMS,
        request_notes: &["official docs say this is only open to selected enterprise customers"],
        source: "https://docs.bigmodel.cn/cn/guide/models/text/glm-5.1-highspeed",
    },
    ModelSpec {
        provider: ProviderKind::Zhipu,
        id: "glm-5-turbo",
        tier: "balanced-agent",
        status: "current",
        is_default: false,
        context_tokens: Some(200_000),
        max_output_tokens: Some(128_000),
        thinking: "toggle",
        reasoning_levels: DEFAULT_REASONING_LEVELS,
        cache: "context cache",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &[
            "balanced GLM coding runs",
            "long tasks at lower cost than 5.1",
        ],
        cli_params: THINKING_PARAMS,
        request_notes: &["price page lists GLM-5-Turbo as a lower-cost GLM-5 family option"],
        source: "https://docs.bigmodel.cn/cn/guide/start/model-overview",
    },
    ModelSpec {
        provider: ProviderKind::Zhipu,
        id: "glm-5",
        tier: "base-agent",
        status: "current",
        is_default: false,
        context_tokens: Some(200_000),
        max_output_tokens: Some(128_000),
        thinking: "toggle",
        reasoning_levels: DEFAULT_REASONING_LEVELS,
        cache: "context cache",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &["cost-sensitive GLM coding", "long context"],
        cli_params: THINKING_PARAMS,
        request_notes: &["model overview positions GLM-5 as an agentic engineering base"],
        source: "https://docs.bigmodel.cn/cn/guide/start/model-overview",
    },
    ModelSpec {
        provider: ProviderKind::Zhipu,
        id: "glm-4.7",
        tier: "previous-high",
        status: "current",
        is_default: false,
        context_tokens: Some(200_000),
        max_output_tokens: Some(128_000),
        thinking: "toggle",
        reasoning_levels: DEFAULT_REASONING_LEVELS,
        cache: "context cache",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &["cheaper GLM fallback", "general coding"],
        cli_params: THINKING_PARAMS,
        request_notes: &["prefer GLM-5.1 for highest coding-agent quality"],
        source: "https://docs.bigmodel.cn/cn/guide/start/model-overview",
    },
    ModelSpec {
        provider: ProviderKind::Minimax,
        id: "MiniMax-M3",
        tier: "flagship-frontier",
        status: "current",
        is_default: true,
        context_tokens: Some(1_000_000),
        max_output_tokens: None,
        thinking: "interleaved thinking native",
        reasoning_levels: MINIMAX_REASONING_LEVELS,
        cache: "cache read pricing; usage may expose cache hit/miss",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &["latest MiniMax coding", "agentic reasoning", "long context"],
        cli_params: MINIMAX_PARAMS,
        request_notes: &["OpenAI-compatible request enables reasoning_split by default"],
        source: "https://platform.minimax.io/docs/api-reference/api-overview",
    },
    ModelSpec {
        provider: ProviderKind::Minimax,
        id: "MiniMax-M2.7",
        tier: "flagship-previous",
        status: "current",
        is_default: false,
        context_tokens: Some(204_800),
        max_output_tokens: None,
        thinking: "interleaved thinking native",
        reasoning_levels: MINIMAX_REASONING_LEVELS,
        cache: "cache read/write pricing",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &["stable MiniMax coding", "M2.7 token plans"],
        cli_params: MINIMAX_PARAMS,
        request_notes: &["highspeed variant has same quality with lower latency"],
        source: "https://platform.minimax.io/docs/api-reference/api-overview",
    },
    ModelSpec {
        provider: ProviderKind::Minimax,
        id: "MiniMax-M2.7-highspeed",
        tier: "flagship-fast",
        status: "plan-gated",
        is_default: false,
        context_tokens: Some(204_800),
        max_output_tokens: None,
        thinking: "interleaved thinking native",
        reasoning_levels: MINIMAX_REASONING_LEVELS,
        cache: "cache read/write pricing",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &["low latency", "high-speed subscription"],
        cli_params: MINIMAX_PARAMS,
        request_notes: &["requires high-speed plan on some accounts"],
        source: "https://platform.minimax.io/docs/api-reference/api-overview",
    },
    ModelSpec {
        provider: ProviderKind::Minimax,
        id: "MiniMax-M2.5",
        tier: "budget-agent",
        status: "current",
        is_default: false,
        context_tokens: Some(204_800),
        max_output_tokens: None,
        thinking: "interleaved thinking native",
        reasoning_levels: MINIMAX_REASONING_LEVELS,
        cache: "cache read/write pricing",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &["lower-cost MiniMax coding", "smoke and dogfood"],
        cli_params: MINIMAX_PARAMS,
        request_notes: &["official docs mark this as value-focused"],
        source: "https://platform.minimax.io/docs/api-reference/api-overview",
    },
    ModelSpec {
        provider: ProviderKind::Qwen,
        id: "qwen3.7-max",
        tier: "flagship",
        status: "current",
        is_default: true,
        context_tokens: Some(1_000_000),
        max_output_tokens: Some(64_000),
        thinking: "toggle via enable_thinking",
        reasoning_levels: QWEN_REASONING_LEVELS,
        cache: "context cache discount; OpenAI-compatible usage may not expose hit/miss",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &[
            "highest Qwen quality",
            "complex reasoning",
            "large repositories",
        ],
        cli_params: THINKING_PARAMS,
        request_notes: &["text generation docs recommend qwen3.7-max for the high-capability tier"],
        source: "https://help.aliyun.com/zh/model-studio/text-generation-model",
    },
    ModelSpec {
        provider: ProviderKind::Qwen,
        id: "qwen3.7-max-2026-05-20",
        tier: "flagship-pinned",
        status: "current",
        is_default: false,
        context_tokens: Some(1_000_000),
        max_output_tokens: Some(64_000),
        thinking: "toggle via enable_thinking",
        reasoning_levels: QWEN_REASONING_LEVELS,
        cache: "context cache discount",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &["pinned qwen3.7-max behavior", "reproducible evals"],
        cli_params: THINKING_PARAMS,
        request_notes: &["current qwen3.7-max points to this dated model in pricing docs"],
        source: "https://help.aliyun.com/zh/model-studio/model-pricing",
    },
    ModelSpec {
        provider: ProviderKind::Qwen,
        id: "qwen3.6-plus",
        tier: "balanced",
        status: "current",
        is_default: false,
        context_tokens: Some(1_000_000),
        max_output_tokens: Some(64_000),
        thinking: "toggle via enable_thinking",
        reasoning_levels: QWEN_REASONING_LEVELS,
        cache: "context cache discount; OpenAI-compatible usage may not expose hit/miss",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &[
            "balanced capability and cost",
            "large repos",
            "tool support",
        ],
        cli_params: THINKING_PARAMS,
        request_notes: &["previous Bamboo default; keep selectable for cost-sensitive runs"],
        source: "https://help.aliyun.com/zh/model-studio/text-generation-model",
    },
    ModelSpec {
        provider: ProviderKind::Qwen,
        id: "qwen3.6-flash",
        tier: "budget-fast",
        status: "current",
        is_default: false,
        context_tokens: Some(1_000_000),
        max_output_tokens: Some(64_000),
        thinking: "toggle via enable_thinking",
        reasoning_levels: QWEN_REASONING_LEVELS,
        cache: "context cache discount",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &["cheap retries", "smoke tests", "fast coding loops"],
        cli_params: THINKING_PARAMS,
        request_notes: &["same 1M context tier as qwen3.6-plus in text generation docs"],
        source: "https://help.aliyun.com/zh/model-studio/text-generation-model",
    },
    ModelSpec {
        provider: ProviderKind::Qwen,
        id: "qwen3.6-max-preview",
        tier: "preview",
        status: "preview",
        is_default: false,
        context_tokens: Some(256_000),
        max_output_tokens: Some(64_000),
        thinking: "toggle via enable_thinking",
        reasoning_levels: QWEN_REASONING_LEVELS,
        cache: "context cache discount",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &["preview evals", "pinned experiments"],
        cli_params: THINKING_PARAMS,
        request_notes: &["preview model; avoid as production default"],
        source: "https://help.aliyun.com/zh/model-studio/text-generation-model",
    },
    ModelSpec {
        provider: ProviderKind::Stepfun,
        id: "step-3.7-flash",
        tier: "flagship-agent",
        status: "current",
        is_default: true,
        context_tokens: Some(256_000),
        max_output_tokens: None,
        thinking: "native reasoning effort; default high for Bamboo coding runs",
        reasoning_levels: STEPFUN_REASONING_LEVELS,
        cache: "prompt cache pricing; usage may expose cached tokens",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &[
            "agentic coding",
            "tool-heavy autonomous runs",
            "multimodal and long-context tasks",
        ],
        cli_params: STEPFUN_PARAMS,
        request_notes: &[
            "standard China API uses https://api.stepfun.com/v1; global keys use https://api.stepfun.ai/v1",
            "Step Plan subscription keys may require https://api.stepfun.com/step_plan/v1",
        ],
        source: "https://platform.stepfun.ai/docs/en/guides/models/step-3.7-flash",
    },
    ModelSpec {
        provider: ProviderKind::Stepfun,
        id: "step-3.5-flash",
        tier: "previous-agent",
        status: "current",
        is_default: false,
        context_tokens: Some(256_000),
        max_output_tokens: None,
        thinking: "native reasoning effort",
        reasoning_levels: STEPFUN_REASONING_LEVELS,
        cache: "prompt cache pricing",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &["Step Plan fallback", "fast agent loops"],
        cli_params: STEPFUN_PARAMS,
        request_notes: &["Step Plan docs still list this as a recommended verification model"],
        source: "https://platform.stepfun.com/docs/zh/step-plan/integrations/reasoning-api",
    },
    ModelSpec {
        provider: ProviderKind::Stepfun,
        id: "step-3.5-flash-2603",
        tier: "agent-optimized",
        status: "current",
        is_default: false,
        context_tokens: Some(256_000),
        max_output_tokens: None,
        thinking: "native reasoning effort",
        reasoning_levels: STEPFUN_REASONING_LEVELS,
        cache: "prompt cache pricing",
        tool_use: "supported",
        structured_output: "supported",
        recommended_for: &["Step Plan optimized coding", "fast tool loops"],
        cli_params: STEPFUN_PARAMS,
        request_notes: &["Step Plan reasoning integration lists this optimized model"],
        source: "https://platform.stepfun.com/docs/zh/step-plan/integrations/reasoning-api",
    },
    ModelSpec {
        provider: ProviderKind::Stepfun,
        id: "step-router-v1",
        tier: "router",
        status: "current",
        is_default: false,
        context_tokens: Some(256_000),
        max_output_tokens: None,
        thinking: "router-selected",
        reasoning_levels: STEPFUN_REASONING_LEVELS,
        cache: "actual routed model pricing",
        tool_use: "supported with routed-model caveats",
        structured_output: "supported with routed-model caveats",
        recommended_for: &["Step Plan cost-quality routing", "experiments"],
        cli_params: STEPFUN_PARAMS,
        request_notes: &[
            "routes between DeepSeek and Step models; cost should be read from actual usage/billing when available",
        ],
        source: "https://platform.stepfun.com/docs/zh/step-plan/integrations/reasoning-api",
    },
];

pub fn builtin_models(provider: ProviderKind) -> impl Iterator<Item = &'static ModelSpec> {
    BUILTIN_MODELS
        .iter()
        .filter(move |model| model.provider == provider)
}

pub fn builtin_model(provider: ProviderKind, id: &str) -> Option<&'static ModelSpec> {
    BUILTIN_MODELS
        .iter()
        .find(|model| model.provider == provider && model.id.eq_ignore_ascii_case(id))
}

pub fn provider_for_model(id: &str) -> Option<ProviderKind> {
    BUILTIN_MODELS
        .iter()
        .find(|model| model.id.eq_ignore_ascii_case(id))
        .map(|model| model.provider)
}

pub fn builtin_models_for<'a>(
    providers: &'a [ProviderKind],
) -> impl Iterator<Item = &'static ModelSpec> + 'a {
    BUILTIN_MODELS
        .iter()
        .filter(move |model| providers.contains(&model.provider))
}

pub fn provider_params(provider: ProviderKind) -> ProviderParamSpec {
    match provider {
        ProviderKind::Deepseek => ProviderParamSpec {
            provider,
            thinking_mapping: "thinking: {\"type\": \"enabled|disabled\"}",
            reasoning_effort_mapping: "reasoning_effort",
            max_tokens_mapping: "max_tokens",
            cache_mapping: "provider native prefix cache; usage exposes hit/miss when returned",
            supported_cli_params: DEEPSEEK_PARAMS,
            passthrough: "--param KEY=JSON is merged into the OpenAI-compatible request body unless KEY is reserved",
        },
        ProviderKind::Xiaomi => ProviderParamSpec {
            provider,
            thinking_mapping: "thinking: {\"type\": \"enabled|disabled\"}",
            reasoning_effort_mapping: "not supported by current OpenAI-compatible mapping",
            max_tokens_mapping: "max_completion_tokens",
            cache_mapping: "provider native cache; usage exposes hit/miss",
            supported_cli_params: THINKING_PARAMS,
            passthrough: "--param KEY=JSON is merged into the OpenAI-compatible request body unless KEY is reserved",
        },
        ProviderKind::Kimi => ProviderParamSpec {
            provider,
            thinking_mapping: "thinking: {\"type\": \"enabled|disabled\"}",
            reasoning_effort_mapping: "not supported by current OpenAI-compatible mapping",
            max_tokens_mapping: "max_completion_tokens",
            cache_mapping: "prompt_cache_key is sent when available",
            supported_cli_params: THINKING_PARAMS,
            passthrough: "--param KEY=JSON is merged into the OpenAI-compatible request body unless KEY is reserved",
        },
        ProviderKind::Zhipu => ProviderParamSpec {
            provider,
            thinking_mapping: "thinking: {\"type\": \"enabled|disabled\"}",
            reasoning_effort_mapping: "not supported by current OpenAI-compatible mapping",
            max_tokens_mapping: "max_tokens",
            cache_mapping: "provider native context cache; usage exposes hit/miss",
            supported_cli_params: THINKING_PARAMS,
            passthrough: "--param KEY=JSON is merged into the OpenAI-compatible request body unless KEY is reserved",
        },
        ProviderKind::Minimax => ProviderParamSpec {
            provider,
            thinking_mapping: "reasoning_split: true",
            reasoning_effort_mapping: "native interleaved thinking; no effort enum in current mapping",
            max_tokens_mapping: "max_completion_tokens",
            cache_mapping: "provider native cache/read pricing",
            supported_cli_params: MINIMAX_PARAMS,
            passthrough: "--param KEY=JSON is merged into the OpenAI-compatible request body unless KEY is reserved",
        },
        ProviderKind::Qwen => ProviderParamSpec {
            provider,
            thinking_mapping: "enable_thinking: true|false",
            reasoning_effort_mapping: "OpenAI-compatible chat uses enable_thinking; Responses API supports reasoning.effort separately",
            max_tokens_mapping: "max_tokens",
            cache_mapping: "provider context cache discount; hit/miss may not be exposed in OpenAI-compatible usage",
            supported_cli_params: THINKING_PARAMS,
            passthrough: "--param KEY=JSON is merged into the OpenAI-compatible request body unless KEY is reserved",
        },
        ProviderKind::Stepfun => ProviderParamSpec {
            provider,
            thinking_mapping: "no boolean thinking field; --thinking disabled lowers reasoning_effort to low",
            reasoning_effort_mapping: "reasoning_effort: low|medium|high",
            max_tokens_mapping: "max_tokens",
            cache_mapping: "provider prompt cache pricing; usage may expose cached_tokens",
            supported_cli_params: STEPFUN_PARAMS,
            passthrough: "--param KEY=JSON is merged into the OpenAI-compatible request body unless KEY is reserved",
        },
        ProviderKind::Openai => ProviderParamSpec {
            provider,
            thinking_mapping: "provider-specific",
            reasoning_effort_mapping: "reasoning_effort",
            max_tokens_mapping: "max_tokens or max_completion_tokens based on model",
            cache_mapping: "prompt_cache_key and prompt_cache_retention",
            supported_cli_params: DEEPSEEK_PARAMS,
            passthrough: "--param KEY=JSON is merged into the OpenAI-compatible request body unless KEY is reserved",
        },
        ProviderKind::Anthropic => ProviderParamSpec {
            provider,
            thinking_mapping: "thinking: {type, budget_tokens}",
            reasoning_effort_mapping: "mapped to budget_tokens",
            max_tokens_mapping: "max_tokens",
            cache_mapping: "cache_control ephemeral blocks",
            supported_cli_params: COMMON_PARAMS,
            passthrough: "not supported by Anthropic-compatible request mapping",
        },
    }
}

pub fn provider_param_specs(providers: &[ProviderKind]) -> Vec<ProviderParamSpec> {
    providers.iter().copied().map(provider_params).collect()
}

#[allow(dead_code)]
pub fn format_token_count(value: Option<u64>) -> String {
    let Some(value) = value else {
        return "n/a".to_string();
    };
    if value >= 1_000_000 && value % 1_000_000 == 0 {
        format!("{}M", value / 1_000_000)
    } else if value >= 1_000 && value % 1_000 == 0 {
        format!("{}K", value / 1_000)
    } else {
        value.to_string()
    }
}
